[package]
name = "rust-interactive-bill-manager"
version = "0.1.0"
edition = "2021"
author = "Paul M."
license = "MIT"

[lib]
name = "demo"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
